baseURL: 'http://sth.cludisciples.cyou/'
languageCode: 'en-us'
title: 'Chouverse TRIAL'
theme: 'basic'
Paginate: 10
disqusShortname: "hugo-trial-aa1874"

params:
  author: "Someone"
  description: >
    Craft something great.
  gh_url: "https://api.github.com/users"
  gh_user: "aa1874"

permalinks:
  posts: "posts/:year/:month/:slug/"
  year: "/posts/:slug/"
  month: "/posts/:slug/"

taxonomies:
  year: "year"
  month: "month"
  tag: "tags"
  category: "categories"